version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/backend
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
